### ISSUE TITLE
Account enhancements

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/hoogly#1]
Add the following

1> Repository
2> Business Delegate
3> Controller
4> Unit test

**Comment by Rajiv-mar121** [comment]
Started Working...

**Comment by Rajiv-mar121** [comment]
Code pushed please review once .

Junit test for method testFindAll() is failing . I am checking this .

Regards,
Rajiv

**Comment by Rajiv-mar121** [comment]
Branch : 01_account_repo_services

**Comment by kdhrubo** [comment]
Code looks good. Ensure all junits are green before merge.

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

Please review the code .

#01
Branch : 01_account_repo_services
Now all unit tests are green.

Its ready to merge.

Regards,
Rajiv
