### ISSUE TITLE
Quote module enhancements

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/hoogly#10]
Add the following

1> Repository
2> Business Delegate
3> Controller
4> Unit test

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

Code pushed please review once. Quote domain value I have used String as data types please check once . 
We need to inject reference of Account and Contact and Opportunity here also . How we'll achieve it do we need to add those jar in classpath ?

#10
Branch: 10_quote_files

Regards,
Rajiv

**Comment by kdhrubo** [comment]
In microservices it is adviced that you dont share any jar. So you can keep a reference to account id and contact id. That will save expensive joins on the database.
